version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/angular-frontend

hooks:

  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root