version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install -g @angular/cli
      - npm install
  
  build:
    commands:
      - ng build --configuration production
      - echo "Adding appspec.yml and scripts to build directory..."
      - cp appspec.yml dist/angular-frontend/  
      - cp -r scripts/ dist/angular-frontend/  
artifacts:
  files:
    - '**/*'  
  base-directory: 'dist/angular-frontend'
  